### ISSUE TITLE
'nginx_sites' semicolon escaping ignores quoted values

### ISSUE THREAD

**Issue by milliams** [jdauphant/ansible-role-nginx#180]
If I set `nginx_sites` to

```yaml
nginx_sites:
  my_site:
    - add_header X-XSS-Protection "1; mode=block"
```

it is converted in the output to
```nginx
server {
   add_header X-XSS-Protection "1;
       mode=block";
}
```

rather than
```nginx
server {
   add_header X-XSS-Protection "1; mode=block";
```
which, as far as I can tell is treated by nginx as simply `1`.

This seems to be caused by the code in `templates/site.conf.j2` which simply does a
```python
v.replace(";",";\n ")
```
and ignores whether the semicolon is inside quotation marks.
