### ISSUE TITLE
default vhost configuration does not work

### ISSUE THREAD

**Issue by abhirama** [jdauphant/ansible-role-nginx#21]
This is how my playbook looks like:

``` yaml

---
- hosts: vagrant 
  remote_user: vagrant 
  sudo: True
  roles:
  - role: jdauphant.nginx      
    nginx_sites: 
      default: 
        - listen *:80 
        - server_name localhost
        - root "/vagrant"
        - index index.html
```

When I run this playbook, under sites-enabled default as well as default.conf files are present due to which localhost requests do not work(default overrides default.conf's server section).

I did a bit of digging around and changed "Disable the default sites" task's when condition from

``` yaml
 when: >
    'default' not in nginx_sites.keys()
```

to

``` yaml
when: "'default' in nginx_sites.keys()"
```

After this change, I find only default.conf in sites-enabled and the configuration I provided for localhost kicks in.

Is this a bug or am I missing something?

Running this on vagrant with config.vm.box = "ubuntu/trusty64".
