### ISSUE TITLE
Does this role need run as root?

### ISSUE THREAD

**Issue by shadycuz** [jdauphant/ansible-role-nginx#216]
It's not mentioned any where I could find easily. 
```
amazon-ebs: TASK [nginx : Set SELinux boolean to allow nginx to set rlimit] ****************
    amazon-ebs: fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Cannot set persistent booleans; please try as root"}
    amazon-ebs: 	to retry, use: --limit @/tmp/packer-provisioner-ansible-local/5abce67b-703c-35d9-699a-3280f4a5056e/playbook.retry
    amazon-ebs:
    amazon-ebs: PLAY RECAP *********************************************************************
    amazon-ebs: 127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=1   
    amazon-ebs:
```
