### ISSUE TITLE
Allow for no default config to be generated

### ISSUE THREAD

**Issue by BenBE** [jdauphant/ansible-role-nginx#234]
The created (and activate) default site (cf. defaults/main.yml) causes interference with configurations where the default host should be configured using a template (either cause a warning about duplicate sites or need to unconfigure things coming from the defaults). Would be nice if there was a simple way to suppress creation of the default site in cases I really want just a bare nginx with only the settings visible in my playbook.

Sample:
```
    - role: service.nginx
      nginx_sites:
        foo:
          template: foo.conf.j2
          server_name: foo.example.org
```

Expected behaviour:
Produces only one site (enabled) named foo.

Actaul behaviour:
Produces two sites (enabled) called default and foo.

Workaround:
```
    - role: service.nginx
      keep_only_specified: true
      nginx_remove_sites:
        - default
      nginx_disabled_sites:
        - default
      nginx_sites:
        foo:
          template: foo.conf.j2
          server_name: foo.example.org
```
NB: Only removing default, without disabling it causes a templating error.

Alternatively /causing a warning on execution) you could override default:
```
    - role: service.nginx
      nginx_sites:
        default:
          template: foo.conf.j2
          server_name: foo.example.org
```
