### ISSUE TITLE
Debian/Ubuntu: Add force=yes to avoid issues

### ISSUE THREAD

**Issue by deimosfr** [jdauphant/ansible-role-nginx#40]
Hi,

Can you please add "force=yes" in the Nginx installation package to avoid issues when installing nginx-extra package for example:
```
  - name: Install the nginx packages
    apt: name={{ item }} state=present force=yes
    with_items: nginx_ubuntu_pkg
    environment: env 
    when: ansible_os_family == "Debian"
    tags: [packages,nginx]
```

I got this kind of issues when not set:
```
    docker: TASK: [jdauphant.nginx | Install the nginx packages] **************************

    docker: failed: [127.0.0.1] => (item=nginx-extras) => {"failed": true, "item": "nginx-extras"}
    docker: stderr: E: There are problems and -y was used without --force-yes
    docker: 
    docker: stdout: Reading package lists...
    docker: Building dependency tree...
    docker: Reading state information...
    docker: The following extra packages will be installed:
    docker: fontconfig-config fonts-dejavu-core libfontconfig1 libfreetype6 libgd3
    docker: libjbig0 libjpeg62-turbo libluajit-5.1-2 libluajit-5.1-common libperl5.20
    docker: libpng12-0 libtiff5 libvpx1 libxpm4 nginx-common
    docker: Suggested packages:
    docker: libgd-tools fcgiwrap nginx-doc ssl-cert
    docker: The following NEW packages will be installed:
    docker: fontconfig-config fonts-dejavu-core libfontconfig1 libfreetype6 libgd3
    docker: libjbig0 libjpeg62-turbo libluajit-5.1-2 libluajit-5.1-common libperl5.20
    docker: libpng12-0 libtiff5 libvpx1 libxpm4 nginx-common nginx-extras
    docker: 0 upgraded, 16 newly installed, 0 to remove and 26 not upgraded.
    docker: Need to get 4368 kB of archives.
    docker: After this operation, 11.2 MB of additional disk space will be used.
    docker: WARNING: The following packages cannot be authenticated!
    docker: libpng12-0 libfreetype6 fonts-dejavu-core fontconfig-config libfontconfig1
    docker: libjpeg62-turbo libjbig0 libtiff5 libvpx1 libxpm4 libgd3
    docker: libluajit-5.1-common libluajit-5.1-2 libperl5.20 nginx-common nginx-extras
    docker: 
    docker: msg: 'apt-get install 'nginx-extras'' failed: E: There are problems and -y was used without --force-yes
```

Thanks
