### ISSUE TITLE
Configure the extension of sites-available config files 

### ISSUE THREAD

**Issue by VoidAndAny** [jdauphant/ansible-role-nginx#56]
First of all thank you for this role, it is very useful.

Is it possible to add a variable allowing to configure the extension of site definition in sites-available ?
For the moment the role always add .conf extension.

```
- name: Create the configurations for sites
  template: src=site.conf.j2 dest={{nginx_conf_dir}}/sites-available/{{ item }}{{nginx_config_extension|default()}}
  with_items: nginx_sites.keys()
  notify: 
   - restart nginx
  tags: [configuration,nginx]
```

I can make a pull request if you want, let me know if your agree with my variable name.
