### ISSUE TITLE
upstream use with multitenant setup?

### ISSUE THREAD

**Issue by simon-weber** [jdauphant/ansible-role-nginx#58]
I've got one server with multiple projects running on it. Each project has an application server behind nginx, so each defines one site and one upstream. I'll call these site1/upstream1 and site2/upstream2.

It looks like the config deals properly with the multiple `nginx_site` definition, but clobbers the other `upstream` definition. If I run ansible for site1, then site2, I get output that looks like:

```
TASK: [jdauphant.nginx | Check nginx syntax of configuration files] ***********
failed: [...] => {"changed": true, "cmd": "nginx -t", "delta": "0:00:00.693414", "end": "2015-06-27 20:27:20.640370", "rc": 1, "start": "2015-06-27 20:27:19.946956", "stdout_lines": [], "warnings": []}
stderr: nginx: [emerg] host not found in upstream "upstream1" in /etc/nginx/sites-enabled/site1.conf:10
nginx: configuration file /etc/nginx/nginx.conf test failed
```

Is this expected? Or is there a better way to set up my configuration to avoid this? I'm pretty new to nginx in general.

**Comment by simon-weber** [comment]
Maybe this could be fixed by namespacing the files that end up underneath conf.d?

**Comment by jdauphant** [comment]
Hello @simon-weber ,

I need to more informations : 
- where have you declared upstream1 ?
- can you provide a example of your configuration ?

Best regards,
Julien

**Comment by simon-weber** [comment]
Sure thing. Here's an example configuration: https://github.com/simon-weber/instant-discourse/blob/master/ops/webservers.yml.

The second config is copied from that one and has a different site and upstream name.

**Comment by simon-weber** [comment]
Oh, I bet configs maps onto filename, haha. So I should just drop those settings into app-specific config blocks?

**Comment by jdauphant** [comment]
Config name match with file name.
- do you run the config twice on the server ?
- if it's the case, do you name differently the configuration in nginx_sites and nginx_config ?

For example :
```yaml
      nginx_sites:
        default: # create or replace file name /etc/nginx/conf.d/default.conf
          - listen {{ http_port if http_port != 443 else '443 ssl' }}
# [...]
      nginx_configs:
        upstream: # create or replace file name /etc/nginx/site-available/upstream.conf
            - upstream tornado { server 127.0.0.1:{{ tornado_port }}; }
        map: # create or replace file name /etc/nginx/site-available/map.conf
            - map $http_upgrade $connection_upgrade {
                  default upgrade;
                  '' close;
              }
```
