### ISSUE TITLE
How to use this role as a dependency ?

### ISSUE THREAD

**Issue by Seraf** [jdauphant/ansible-role-nginx#63]
Hello,

I'm trying to create a phpmyadmin role which will install the package and create the nginx vhost using your nginx role.

The problem is when I call your role as a dependency, the role is called before the package install. So the path does not exist yet and nginx will fail as root path doesn't exist.

Any idea about this please ? Maybe a flag to not reload nginx and let my role manage nginx daemon with his own handler ?

If you think the flag is the good way to manage this usecase, I will do a PR with no breaking change.

Thanks

**Comment by jdauphant** [comment]
Hello,

I don't use dependencies :( 

Here is some example usage than can help you :

# Basic usage
```yaml
roles:
 - phpmyadmin
 - role: nginx
   nginx_sites:
     phpmyadmin:
        listen 80
        server_name localhost
        root "/var/www/phpmyadmin"
```

# Use a variable of another role
```yaml
roles:
 - phpmyadmin
 - role: nginx
   nginx_sites:
     phpmyadmin: "{{phpmyadmin_nginx_config}}"  // phpmyadmin_nginx_config can be defined in phpmyadmin
```

# Multi call of this role
```yaml
- role: nginx // for the packages installation
  nginx_sites: [] // you can declare your default pages
- phpmyadmin
- role: nginx
  nginx_installation_type: "configuration-only" // you can change configuration-only by whatever you want except packages
  nginx_sites:
     phpmyadmin: "{{phpmyadmin_nginx_config}}"
```

Maybe the last one could be use with dependency mode.

Hope this can help you,
Julien
